version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: api-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    image: api-app
    ports:
      - '3000:3000'
    env_file:
      - ./apps/chat-api/.env.prod
  ui:
    image: ui-app
    ports:
      - '4200:80'
    container_name: ui-app
    volumes:
    - ./apps/chat-ui/src/configuration.prod.json:/usr/share/nginx/html/assets/configuration.json
volumes:
  db:
    driver: local
